### ISSUE TITLE
shellHistory not starting with #

### ISSUE THREAD

**Issue by abakermi** [BharatKalluri/harmony#8]
shell history at `~/.bash_history` is a text files , each comnans fit one line or more , so you can't use
`historyItemsStrArr := strings.Split(string(shellHistory), "#")`

I suggest that you use a scanner like that :

```
scanner := bufio.NewScanner(strings.NewReader(string(shellHistory)))
	for scanner.Scan() {
//..
}

```

**Comment by BharatKalluri** [comment]
Let me know if I misunderstood your point. 

The bash history file is supposed to have timestamps associated with each command. So that harmony can get an idea of which command executed in what order. By default, bash does not store the timestamps. And if the timestamp is not present, harmony fails. This is expected behaviour. 
The # split was done, assuming there are timestamps in the file. Timestamps start with an `#`. If they were not present, harmony was failing silently. 
I've made it fail more explicitly now, and also added clear documentation over at https://github.com/BharatKalluri/harmony#note-to-bash-users

Thanks 👍🏽
